apiVersion: v1
kind: Service
metadata:
  name: {{ template "fortune.fullname" . }}
  labels:
    app: {{ template "fortune.name" . }}
    chart: {{ template "fortune.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ template "fortune.name" . }}
    release: {{ .Release.Name }}
